[package]
name = "bitcoin-miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.1"
bitcoincore-rpc = "0.17.0"
dotenv = "0.15.0"
hex = "0.4.3"
num_cpus = "1.16.0"
